apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: weekly-pod-failure
  namespace: chaos-testing
spec:
  schedule: "0 2 * * 3"
  historyLimit: 5
  concurrencyPolicy: Forbid
  type: PodChaos
  podChaos:
    action: pod-failure
    mode: all
    selector:
      namespaces:
        - default
    duration: "5m"